Connor Kowalski
9/23/26
Instagram likes & following data report

In [1]:
import json
import pandas as pd

with open("liked_posts.json", "r") as f:
    data = json.load(f)

data[0]

{'timestamp': 1789483004,
 'media': [],
 'label_values': [{'label': 'URL',
   'value': 'https://www.instagram.com/reel/DdTDvpjNY4D/',
   'href': 'https://www.instagram.com/reel/DdTDvpjNY4D/'},
  {'label': 'Caption',
   'value': 'TVã\x82¢ã\x83\x8bã\x83¡ã\x80\x8eONE PIECEã\x80\x8fã\x82¨ã\x83«ã\x83\x90ã\x83\x95ç·¨æ\x9c\x80æ\x96°æ\x83\x85å\xa0±ã\x82\x92ç\x99ºè¡¨ï¼\x86æ\x9c\x80æ\x96°PVå\x85¬é\x96\x8b ã\x82ªã\x83¼ã\x83\x97ã\x83\x8bã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8cï¼\x86ã\x82¨ã\x83³ã\x83\x87ã\x82£ã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8cã\x80\x81ã\x81\x95ã\x82\x89ã\x81«ã\x82¨ã\x83«ã\x83\x90ã\x83\x95ç·¨ã\x81®é\x87\x8dè¦\x81ã\x82\xadã\x83£ã\x83©ã\x82¯ã\x82¿ã\x83¼ã\x80\x8cã\x83\xadã\x82\xadã\x80\x8dã\x81®ã\x82\xadã\x83£ã\x82¹ã\x83\x88ã\x81\x8cæ±ºå®\x9aã\x81\x97ã\x81¾ã\x81\x97ã\x81\x9f!! ã\x82ªã\x83¼ã\x83\x97ã\x83\x8bã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8c:'},
  {'label': 'Title', 'value': ''},
  {'dict': [], 'title': 'Hashtags'},
  {'dict': [{'dict': [{'label': 'URL', 'value': ''},
      {'label': 'Name', 'value': ''},
      {'label': 'Username', 'value': 'yiocuh'}],
     'title': ''}],
   'title': 'Owner'},
  {'dict': [], 'title': 'Brand partner'}],
 'fbid': '18117014230978370'}

In [2]:
row = {}
row['timestamp'] = data[0]['timestamp']

row

{'timestamp': 1789483004}

In [3]:
for item in data[0]['label_values']:
    if 'label' in item:
        row[item['label']] = item['value']

row

{'timestamp': 1789483004,
 'URL': 'https://www.instagram.com/reel/DdTDvpjNY4D/',
 'Caption': 'TVã\x82¢ã\x83\x8bã\x83¡ã\x80\x8eONE PIECEã\x80\x8fã\x82¨ã\x83«ã\x83\x90ã\x83\x95ç·¨æ\x9c\x80æ\x96°æ\x83\x85å\xa0±ã\x82\x92ç\x99ºè¡¨ï¼\x86æ\x9c\x80æ\x96°PVå\x85¬é\x96\x8b ã\x82ªã\x83¼ã\x83\x97ã\x83\x8bã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8cï¼\x86ã\x82¨ã\x83³ã\x83\x87ã\x82£ã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8cã\x80\x81ã\x81\x95ã\x82\x89ã\x81«ã\x82¨ã\x83«ã\x83\x90ã\x83\x95ç·¨ã\x81®é\x87\x8dè¦\x81ã\x82\xadã\x83£ã\x83©ã\x82¯ã\x82¿ã\x83¼ã\x80\x8cã\x83\xadã\x82\xadã\x80\x8dã\x81®ã\x82\xadã\x83£ã\x82¹ã\x83\x88ã\x81\x8cæ±ºå®\x9aã\x81\x97ã\x81¾ã\x81\x97ã\x81\x9f!! ã\x82ªã\x83¼ã\x83\x97ã\x83\x8bã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8c:',
 'Title': ''}

In [4]:
for item in data[0]['label_values']:
    if 'label' in item:
        row[item['label']] = item['value']
    elif item.get('title') == 'Owner':
        owner_fields = item['dict'][0]['dict']
        for owner_item in owner_fields:
            row['Owner ' + owner_item['label']] = owner_item['value']
        
row

{'timestamp': 1789483004,
 'URL': 'https://www.instagram.com/reel/DdTDvpjNY4D/',
 'Caption': 'TVã\x82¢ã\x83\x8bã\x83¡ã\x80\x8eONE PIECEã\x80\x8fã\x82¨ã\x83«ã\x83\x90ã\x83\x95ç·¨æ\x9c\x80æ\x96°æ\x83\x85å\xa0±ã\x82\x92ç\x99ºè¡¨ï¼\x86æ\x9c\x80æ\x96°PVå\x85¬é\x96\x8b ã\x82ªã\x83¼ã\x83\x97ã\x83\x8bã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8cï¼\x86ã\x82¨ã\x83³ã\x83\x87ã\x82£ã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8cã\x80\x81ã\x81\x95ã\x82\x89ã\x81«ã\x82¨ã\x83«ã\x83\x90ã\x83\x95ç·¨ã\x81®é\x87\x8dè¦\x81ã\x82\xadã\x83£ã\x83©ã\x82¯ã\x82¿ã\x83¼ã\x80\x8cã\x83\xadã\x82\xadã\x80\x8dã\x81®ã\x82\xadã\x83£ã\x82¹ã\x83\x88ã\x81\x8cæ±ºå®\x9aã\x81\x97ã\x81¾ã\x81\x97ã\x81\x9f!! ã\x82ªã\x83¼ã\x83\x97ã\x83\x8bã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8c:',
 'Title': '',
 'Owner URL': '',
 'Owner Name': '',
 'Owner Username': 'yiocuh'}

In [5]:
tidy_rows = []

for entry in data:
    row = {}
    row['timestamp'] = entry['timestamp']

    for item in entry['label_values']:
        if 'label' in item:
            row[item['label']] = item['value']
        elif item.get('title') == 'Owner':
            owner_fields = item['dict'][0]['dict']
            for owner_item in owner_fields:
                row['Owner ' + owner_item['label']] = owner_item['value']
    tidy_rows.append(row)

tidy_rows[:2]

[{'timestamp': 1789483004,
  'URL': 'https://www.instagram.com/reel/DdTDvpjNY4D/',
  'Caption': 'TVã\x82¢ã\x83\x8bã\x83¡ã\x80\x8eONE PIECEã\x80\x8fã\x82¨ã\x83«ã\x83\x90ã\x83\x95ç·¨æ\x9c\x80æ\x96°æ\x83\x85å\xa0±ã\x82\x92ç\x99ºè¡¨ï¼\x86æ\x9c\x80æ\x96°PVå\x85¬é\x96\x8b ã\x82ªã\x83¼ã\x83\x97ã\x83\x8bã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8cï¼\x86ã\x82¨ã\x83³ã\x83\x87ã\x82£ã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8cã\x80\x81ã\x81\x95ã\x82\x89ã\x81«ã\x82¨ã\x83«ã\x83\x90ã\x83\x95ç·¨ã\x81®é\x87\x8dè¦\x81ã\x82\xadã\x83£ã\x83©ã\x82¯ã\x82¿ã\x83¼ã\x80\x8cã\x83\xadã\x82\xadã\x80\x8dã\x81®ã\x82\xadã\x83£ã\x82¹ã\x83\x88ã\x81\x8cæ±ºå®\x9aã\x81\x97ã\x81¾ã\x81\x97ã\x81\x9f!! ã\x82ªã\x83¼ã\x83\x97ã\x83\x8bã\x83³ã\x82°ä¸»é¡\x8cæ\xad\x8c:',
  'Title': '',
  'Owner URL': '',
  'Owner Name': '',
  'Owner Username': 'yiocuh'},
 {'timestamp': 1789446770,
  'URL': 'https://www.instagram.com/reel/DdQhHGkIS0b/',
  'Caption': 'Ø¨Ø±Ø§Û\x8c Ø§Ø·Ù\x84Ø§Ø¹ Ø§Ø² Ù\x82Û\x8cÙ\x85Øª Ø±Ù\x88Ø² Ù\x84Ø·Ù\x81Ø§Ù\x8b Ø¯Ø§Û\x8cØ±Ú©Øª Ù¾Û\x8cØ§Ù\x85 Ø¨Ø¯Û\x8cÙ\x86 ð\x9f\x92\x8cð\x9f\x99\x8f\n\nÙ\x81Ù\x84Ø´ 8 Ú¯Û\x8cÚ¯ Ù\x88Ø±Û\x8cØªÛ\x8c Verity V804\n\nâ\x9c´ï¸\x8fØ´Ù\x86Ø§Ø³Ù\x87 Ù\x85Ø\xadØµÙ\x88Ù\x84 1557126\n\nâ\x9c\x94ï¸\x8fÚ¯Ø§Ø±Ø§Ù\x86ØªÛ\x8c 24 Ù\x85Ø§Ù\x87Ù\x87 Ø¢Ø³Ø§Ù\x86 Ø³Ø±Ù\x88Û\x8cØ³\n\nÛ¶Û³Û°Û°â\x9c³ï¸\x8fÙ\x85Ù\x86Ø§Ø³Ø¨ Ø¬Ù\x87Øª Ø°Ø®Û\x8cØ±Ù\x87 Ø³Ø§Ø²Û\x8c Ù\x88 Ø§Ù\x86ØªÙ\x82Ø§Ù\x84 Ø¯Ø§Ø¯Ù\x87 Ù\x87Ø§ Ù\x86Ø¸Û\x8cØ± Ø¹Ú©Ø³Ø\x8c Ù\x81Û\x8cÙ\x84Ù\x85 Ù\x88 â\x80¦\n\nØ¨Ø¯Ù\x86Ù\x87 Ø³Ø§Ø®ØªÙ\x87 Ø´Ø¯Ù\x87 Ø§Ø² Ù\x81Ù\x84Ø² Ù\x85Ù\x82Ø§Ù\x88Ù\x85 Ø¯Ø± Ø¨Ø±Ø§Ø¨Ø± Ø´Ù\x88Ú© Ù\x88 Ø¶Ø¯ Ø¢Ø¨\n\nÚ©Ø§Ù\x86Ú©ØªÙ\x88Ø± Ø§Ø² Ù\x86Ù\x88Ø¹ USB 2.0 Ø¨Ø§ Ø¸Ø±Ù\x81Û\x8cØª 8 Ú¯Û\x8cÚ¯Ø§Ø¨Ø§Û\x8cØªÛ\x8c\n\nØ¯Ø§Ø±Ø§Û\x8c Ø´Û\x8cØ§Ø± Ø¬Ù\x87Øª Ø§ØªØµØ§Ù\x84 Ø¨Ù\x86Ø¯ Ø¨Ù\x87 Ù\x81Ù\x84Ø´\n\n______________________________\n\nØ³Ù\x81Ø§Ø±Ø´ : Ø¯Ø§Û\x8cØ±Ú©Øªð\x9f\x91\x87ð\x9f\x91\x87\n\nð\x9f\x93±Ù\x88Ø§ØªØ³Ø§Ù¾: Û°Û¹Û°Û³Û²Û°Û¹Û°Û¶Û²Û±\n\nð\x9f\x9a\x9aØ§Ø±Ø³Ø§Ù\x84 Ø±Ø§Û\x8cÚ¯Ø§Ù\x86 Ø¨Ù\x87 Ø³Ø±Ø§Ø³Ø± Ú©Ø´Ù\x88Ø±ð\x9f\x8c\x8f\n\n@nitsar_mobile64\n@nitsar_mobile64\n@nitsar_mobile64\n_______________________________\n\n#Ù\x81Ù\x84Ø´_Û¸Ú¯Û\x8cÚ¯\n#Ù\x81Ù\x84Ø´_Ø¹Ø±Ù\x88Ø³Ú©Û\x8c \n#Ù\x81Ù\x84Ø´_Ù\x85Ù\x85Ù\x88Ø±Û\x8c#Ù\x81Ù\x84Ø´Û³Û²Ú¯Û\x8cÚ¯\n#Ø´Û\x8cØ±Ø§Ø²',
  'Title': '',
  'Owner URL': 'http://wa.me/989032090621',
  'Owner Name': 'Ù\x81Ø±Ù\x88Ø´ Ø¢Ù\x86Ù\x84Ø§Û\x8cÙ\x86. ØªÚ© Ù\x81Ø±Ù\x88Ø´Û\x8c',
  'Owner Username': 'nitsarmobile647'}]

In [6]:
likes_df = pd.DataFrame(tidy_rows)
likes_df.head(10)

,timestamp,URL,Caption,Title,Owner URL,Owner Name,Owner Username
0,1789483004,https://www.instagram.com/reel/DdTDvpjNY4D/,TVã¢ãã¡ãONE PIECEãã¨ã«ããç·¨ææ...,,,,yiocuh
1,1789446770,https://www.instagram.com/reel/DdQhHGkIS0b/,Ø¨Ø±Ø§Û Ø§Ø·ÙØ§Ø¹ Ø§Ø² ÙÛÙ Øª Ø±ÙØ² ÙØ·Ù...,,http://wa.me/989032090621,ÙØ±ÙØ´ Ø¢ÙÙØ§ÛÙ. ØªÚ© ÙØ±ÙØ´Û,nitsarmobile647
2,1789397901,https://www.instagram.com/reel/DdIUHvpiaHb/,"""TVT=Ã\nTONE PIECE.\nã¨ã«ããç·¨ ææ°æ...",,,DIAMONDS!,wegotdimonds
3,1789397466,https://www.instagram.com/reel/DdQH21pNeqN/,Stewie knows whatâs up! Vaping is NEVER the ...,,https://dph.sc.gov/health-wellness/injury-toba...,Tobacco-Free South Carolina â¢,tobaccofreesc
4,1789328562,https://www.instagram.com/reel/DdLZ98Bh0HE/,#TVã¢ãã¡ ãONE PIECEã ã¨ã«ããç·¨ æ...,,,IC,incelcheetah
5,1789320706,https://www.instagram.com/reel/DdPC9L2uOpH/,real,,,i am Dr. Wonderful Truth and kaleb ridgeway is...,drwonderfultruth
6,1789226969,https://www.instagram.com/p/Dc3yNBvGxje/,ð­ follow @wtfkezin \nâ§.* follow @reallyke...,,,Kezin,reallykezin
7,1789189768,https://www.instagram.com/reel/DdK8P_NxJTb/,#TVã¢ãã¡ãONE PIECEã ã¨ã«ãããç·¨...,,,Bacon,bacon3890000
8,1789189747,https://www.instagram.com/reel/DdHfD6TBd8l/,#TVã¢ãã¡ãONE PIECEã ã¨ã«ã\nãç·¨ ...,,,,pinchespiderman
9,1789155951,https://www.instagram.com/reel/DbxUCElu45h/,Follow @seis.__ For More Content ð¥\n#seis #...,,https://linktr.ee/Seis6renPlus,6 R E N +,seis.__

In [7]:
likes_df['DateTime'] = pd.to_datetime(likes_df['timestamp'], unit='s')
likes_df[['timestamp', 'DateTime']].head()

    timestamp            DateTime
0  1789483004 2026-09-15 14:36:44
1  1789446770 2026-09-15 04:32:50
2  1789397901 2026-09-14 14:58:21
3  1789397466 2026-09-14 14:51:06
4  1789328562 2026-09-13 19:42:42

In [8]:
likes_df.head(10)

,timestamp,URL,Caption,Title,Owner URL,Owner Name,Owner Username,DateTime
0,1789483004,https://www.instagram.com/reel/DdTDvpjNY4D/,TVã¢ãã¡ãONE PIECEãã¨ã«ããç·¨ææ...,,,,yiocuh,2026-09-15 14:36:44
1,1789446770,https://www.instagram.com/reel/DdQhHGkIS0b/,Ø¨Ø±Ø§Û Ø§Ø·ÙØ§Ø¹ Ø§Ø² ÙÛÙ Øª Ø±ÙØ² ÙØ·Ù...,,http://wa.me/989032090621,ÙØ±ÙØ´ Ø¢ÙÙØ§ÛÙ. ØªÚ© ÙØ±ÙØ´Û,nitsarmobile647,2026-09-15 04:32:50
2,1789397901,https://www.instagram.com/reel/DdIUHvpiaHb/,"""TVT=Ã\nTONE PIECE.\nã¨ã«ããç·¨ ææ°æ...",,,DIAMONDS!,wegotdimonds,2026-09-14 14:58:21
3,1789397466,https://www.instagram.com/reel/DdQH21pNeqN/,Stewie knows whatâs up! Vaping is NEVER the ...,,https://dph.sc.gov/health-wellness/injury-toba...,Tobacco-Free South Carolina â¢,tobaccofreesc,2026-09-14 14:51:06
4,1789328562,https://www.instagram.com/reel/DdLZ98Bh0HE/,#TVã¢ãã¡ ãONE PIECEã ã¨ã«ããç·¨ æ...,,,IC,incelcheetah,2026-09-13 19:42:42
5,1789320706,https://www.instagram.com/reel/DdPC9L2uOpH/,real,,,i am Dr. Wonderful Truth and kaleb ridgeway is...,drwonderfultruth,2026-09-13 17:31:46
6,1789226969,https://www.instagram.com/p/Dc3yNBvGxje/,ð­ follow @wtfkezin \nâ§.* follow @reallyke...,,,Kezin,reallykezin,2026-09-12 15:29:29
7,1789189768,https://www.instagram.com/reel/DdK8P_NxJTb/,#TVã¢ãã¡ãONE PIECEã ã¨ã«ãããç·¨...,,,Bacon,bacon3890000,2026-09-12 05:09:28
8,1789189747,https://www.instagram.com/reel/DdHfD6TBd8l/,#TVã¢ãã¡ãONE PIECEã ã¨ã«ã\nãç·¨ ...,,,,pinchespiderman,2026-09-12 05:09:07
9,1789155951,https://www.instagram.com/reel/DbxUCElu45h/,Follow @seis.__ For More Content ð¥\n#seis #...,,https://linktr.ee/Seis6renPlus,6 R E N +,seis.__,2026-09-11 19:45:51

In [9]:
likes_df.shape

(282, 8)

In [10]:
likes_df['Owner Username'].isna().sum()

np.int64(0)

In [11]:
likes_df.dtypes

timestamp                 int64
URL                         str
Caption                     str
Title                       str
Owner URL                   str
Owner Name                  str
Owner Username              str
DateTime          datetime64[s]
dtype: object

In [12]:
likes_df.groupby("Owner Username")["DateTime"].count()

Owner Username
0x_riq                1
1244567frebchfries    2
17cmdih               1
1spobloo              1
1uhrae                1
                     ..
yurifeetslop          1
zbhateclan            1
zerocontexthub        1
zgradhomigrad         1
zypher_gg1            1
Name: DateTime, Length: 263, dtype: int64

In [13]:
likes_by_account = (
    likes_df.groupby("Owner Username")["DateTime"]
    .count()
    .sort_values(ascending=False)
)
likes_by_account.head(10)

Owner Username
kaazty                   3
ijuggchildren            3
icantstopjuggin          2
deepintelligenthiphop    2
bartekaminski_           2
bartsimpsonrealistic     2
1244567frebchfries       2
heraldhandlebar          2
cazegamingyt             2
dihcheesegenerator       2
Name: DateTime, dtype: int64

A hypothesis that could be tested with other data would be that I don't interact with many accounts other than people I know. I suspect this because I try to not follow any brands or verified accounts to keep my account more personal and social. I never really liked getting my feed clogged with random ads posted by companies or other unwanted content. I much prefer to keep my community small.

The JSON file I picked is the followers and following files. I think this file will help the hypothesis because it will show that i dont follow many people in general, and most of the people who follow me I follow back. I also dont follow many accounts over a few thousand followers.

In [19]:
with open("following.json", "r") as d:
    following = json.load(d)

following

{'relationships_following': [{'title': 'bushey.two',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/bushey.two',
     'timestamp': 1789872277}]},
  {'title': 'indiagamingcs2',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/indiagamingcs2',
     'timestamp': 1789831414}]},
  {'title': 'vaultbox.ai',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/vaultbox.ai',
     'timestamp': 1788917029}]},
  {'title': 'ethe.r3al._',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/ethe.r3al._',
     'timestamp': 1787020015}]},
  {'title': 'quinnofthaworld',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/quinnofthaworld',
     'timestamp': 1779850432}]},
  {'title': 'xraypilot',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/xraypilot',
     'timestamp': 1778810551}]},
  {'title': 'ethanmaso_',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/ethanmaso_',
     'timestamp': 1775362708}]},
  {'title': 'jared_wilson4',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/jared_wilson4',
     'timestamp': 1774364959}]},
  {'title': 'billybobwilliamson_',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/billybobwilliamson_',
     'timestamp': 1774288136}]},
  {'title': 'gideonfry1',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/gideonfry1',
     'timestamp': 1774076412}]},
  {'title': 'wyatt_glendenning',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/wyatt_glendenning',
     'timestamp': 1772252657}]},
  {'title': 'sonfrmva',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/sonfrmva',
     'timestamp': 1769980385}]},
  {'title': 'bushey_won',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/bushey_won',
     'timestamp': 1768616140}]},
  {'title': 'robert_main2',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/robert_main2',
     'timestamp': 1767049632}]},
  {'title': 'ultravioletastronaut',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/ultravioletastronaut',
     'timestamp': 1763482183}]},
  {'title': 'courtneykowalski',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/courtneykowalski',
     'timestamp': 1762144931}]},
  {'title': 'the.rizzard.0f.oz',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/the.rizzard.0f.oz',
     'timestamp': 1762114448}]},
  {'title': 'lexi.drear',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/lexi.drear',
     'timestamp': 1762112817}]},
  {'title': 'sebbim20',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/sebbim20',
     'timestamp': 1761432739}]},
  {'title': 'ace_wedlund',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/ace_wedlund',
     'timestamp': 1757945464}]},
  {'title': 'probably_most_likely_not_liam',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/probably_most_likely_not_liam',
     'timestamp': 1756175337}]},
  {'title': 'tpreston_2',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/tpreston_2',
     'timestamp': 1755996556}]},
  {'title': 'evan_kenney_',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/evan_kenney_',
     'timestamp': 1755296340}]},
  {'title': 'c_smizy',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/c_smizy',
     'timestamp': 1754529370}]},
  {'title': 'sachith_iyer',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/sachith_iyer',
     'timestamp': 1742357183}]},
  {'title': 'wemily2.0',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/wemily2.0',
     'timestamp': 1741378014}]},
  {'title': 'marinara2505',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/marinara2505',
     'timestamp': 1737495176}]},
  {'title': 'dwheels25',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/dwheels25',
     'timestamp': 1736575804}]},
  {'title': 'not_ava_liable19',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/not_ava_liable19',
     'timestamp': 1733376031}]},
  {'title': 'sirbiggusdickuss',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/sirbiggusdickuss',
     'timestamp': 1733112132}]},
  {'title': 'gleepgirl',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/gleepgirl',
     'timestamp': 1730934576}]},
  {'title': 'piperk.98',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/piperk.98',
     'timestamp': 1729969921}]},
  {'title': 'rnan_photoss',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/rnan_photoss',
     'timestamp': 1728203539}]},
  {'title': 'mr_izmir35',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/mr_izmir35',
     'timestamp': 1727223335}]},
  {'title': 'anna_skye6',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/anna_skye6',
     'timestamp': 1726971055}]},
  {'title': 'steveski16',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/steveski16',
     'timestamp': 1723761954}]},
  {'title': 'socksnadia',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/socksnadia',
     'timestamp': 1722394792}]},
  {'title': 'kaitlyn.kowalski',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/kaitlyn.kowalski',
     'timestamp': 1722023027}]},
  {'title': 'deid.ra88',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/deid.ra88',
     'timestamp': 1720064390}]},
  {'title': 'jacobbutts333',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/jacobbutts333',
     'timestamp': 1719891923}]},
  {'title': 'chump474',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/chump474',
     'timestamp': 1718854728}]},
  {'title': 'shocky1298',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/shocky1298',
     'timestamp': 1716991497}]},
  {'title': 'oscarc5409',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/oscarc5409',
     'timestamp': 1711207130}]},
  {'title': 'take_a_look_at_lorton',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/take_a_look_at_lorton',
     'timestamp': 1706981428}]},
  {'title': 'yaboyadub',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/yaboyadub',
     'timestamp': 1701486574}]},
  {'title': 'brandonn.mills',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/brandonn.mills',
     'timestamp': 1701442467}]},
  {'title': 'lorenzoyuk_',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/lorenzoyuk_',
     'timestamp': 1696818621}]},
  {'title': 'zeezty_t',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/zeezty_t',
     'timestamp': 1696818612}]},
  {'title': 'nolimit.jose__',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/nolimit.jose__',
     'timestamp': 1694736301}]},
  {'title': 'tristanmihocko',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/tristanmihocko',
     'timestamp': 1692996321}]},
  {'title': 'bendstraws',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/bendstraws',
     'timestamp': 1687758488}]},
  {'title': 'andrewkowalskii',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/andrewkowalskii',
     'timestamp': 1687286220}]},
  {'title': 'katelyn822822',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/katelyn822822',
     'timestamp': 1684533218}]},
  {'title': 'laidbackangle',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/laidbackangle',
     'timestamp': 1684369214}]},
  {'title': 'just_another2u',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/just_another2u',
     'timestamp': 1682739865}]},
  {'title': 'jkhpwl',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/jkhpwl',
     'timestamp': 1671774079}]},
  {'title': 'ryan.kowalski13',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/ryan.kowalski13',
     'timestamp': 1670821087}]},
  {'title': 'rice.chuu',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/rice.chuu',
     'timestamp': 1662925628}]},
  {'title': 'aybery.hinton',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/aybery.hinton',
     'timestamp': 1660010081}]},
  {'title': 'noe.msrl',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/noe.msrl',
     'timestamp': 1656259987}]},
  {'title': 'tsprag80',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/tsprag80',
     'timestamp': 1655780558}]},
  {'title': 'ranen_larsen',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/ranen_larsen',
     'timestamp': 1654197561}]},
  {'title': 'gluhufferscs',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/gluhufferscs',
     'timestamp': 1650852796}]},
  {'title': 'benpodoff',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/benpodoff',
     'timestamp': 1645532937}]},
  {'title': 'jakegilb3rt',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/jakegilb3rt',
     'timestamp': 1640236019}]},
  {'title': 'miranda.kowalski',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/miranda.kowalski',
     'timestamp': 1639450744}]},
  {'title': 'karivukmanic',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/karivukmanic',
     'timestamp': 1639276118}]},
  {'title': 'kdn.7s',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/kdn.7s',
     'timestamp': 1630902368}]},
  {'title': 'ronkgroup',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/ronkgroup',
     'timestamp': 1628739288}]},
  {'title': 'ricosoco23',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/ricosoco23',
     'timestamp': 1623457581}]},
  {'title': 'ben_jergenof05',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/ben_jergenof05',
     'timestamp': 1621302593}]},
  {'title': 'alexanderdieff',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/alexanderdieff',
     'timestamp': 1609893008}]},
  {'title': 'loganwedlund',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/loganwedlund',
     'timestamp': 1597067434}]},
  {'title': 'free_cow_pics',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/free_cow_pics',
     'timestamp': 1593659679}]},
  {'title': 'mcsleezy_succ',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/mcsleezy_succ',
     'timestamp': 1585188552}]},
  {'title': 'scmswaterfountainreviews',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/scmswaterfountainreviews',
     'timestamp': 1576727071}]},
  {'title': 'smetek.c_',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/smetek.c_',
     'timestamp': 1574960355}]},
  {'title': 'kristykowalski',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/kristykowalski',
     'timestamp': 1561032916}]},
  {'title': 'jared12biggs',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/jared12biggs',
     'timestamp': 1560902316}]},
  {'title': 'dhelcyy',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/dhelcyy',
     'timestamp': 1559048463}]},
  {'title': 'itsactuallyalexk',
   'string_list_data': [{'href': 'https://www.instagram.com/_u/itsactuallyalexk',
     'timestamp': 1558921583}]}]}

In [23]:
type(data)
data.keys()

dict_keys(['relationships_following'])

In [29]:
data['relationships_following'][0].keys()

dict_keys(['title', 'string_list_data'])

In [30]:
item = data['relationships_following'][0]

print(item.keys())
print(item['string_list_data'])

dict_keys(['title', 'string_list_data'])
[{'href': 'https://www.instagram.com/_u/bushey.two', 'timestamp': 1789872277}]

In [36]:
rows = []

for item in data['relationships_following']:
    row = {}

    row['title'] = item['title']
    row['href'] = item['string_list_data'][0]['href']
    row['timestamp'] = item['string_list_data'][0]['timestamp']

    rows.append(row)

df = pd.DataFrame(rows)

df.columns = ['Username', 'Link', 'Timestamp']

df.head(10)

,Username,Link,Timestamp
0,bushey.two,https://www.instagram.com/_u/bushey.two,1789872277
1,indiagamingcs2,https://www.instagram.com/_u/indiagamingcs2,1789831414
2,vaultbox.ai,https://www.instagram.com/_u/vaultbox.ai,1788917029
3,ethe.r3al._,https://www.instagram.com/_u/ethe.r3al._,1787020015
4,quinnofthaworld,https://www.instagram.com/_u/quinnofthaworld,1779850432
5,xraypilot,https://www.instagram.com/_u/xraypilot,1778810551
6,ethanmaso_,https://www.instagram.com/_u/ethanmaso_,1775362708
7,jared_wilson4,https://www.instagram.com/_u/jared_wilson4,1774364959
8,billybobwilliamson_,https://www.instagram.com/_u/billybobwilliamson_,1774288136
9,gideonfry1,https://www.instagram.com/_u/gideonfry1,1774076412

This dataframe represents the 10 most recent accounts I have followed and when that was. I think it's pretty tidy as it is easily readable and organized and formatted in a human-readable way. This data definitely doesn't help my hypothesis as much because it contains way less data than i thought. This json was organized in a dictionary instead of a list so it was a bit hard to convert over so I used claude to help tell me the differences in the syntax and then it was pretty understandable from there.